const {
  ChannelType,
  PermissionFlagsBits,
  EmbedBuilder,
  ActionRowBuilder,
  StringSelectMenuBuilder,
  StringSelectMenuOptionBuilder
} = require('discord.js');

function getDb(loadData) { return loadData(); }
function save(loadData, data, saveData) { saveData(data); }
function guildBucket(db, key, guildId, fallback) {
  db[key] ||= {};
  db[key][guildId] ||= fallback;
  return db[key][guildId];
}
function clamp(v, n=1900){ const s=String(v??'').trim(); return s.length>n?s.slice(0,n-1)+'…':s; }
function resolveMember(guild, id){ return guild.members.cache.get(String(id)) || null; }
function resolveChannel(guild, q){
  const s=String(q||'').trim();
  if(!s) return null;
  const id=s.match(/^<#(\d+)>$/)?.[1] || s.match(/^\d{16,25}$/)?.[0];
  if(id) return guild.channels.cache.get(id) || null;
  const clean=s.replace(/^#/, '').toLowerCase();
  return guild.channels.cache.find(c=>c.name.toLowerCase()===clean) || guild.channels.cache.find(c=>c.name.toLowerCase().includes(clean)) || null;
}
function isAdminish(ctx){ return Boolean(ctx?.isOwner || ctx?.permissions?.includes?.('Administrator') || ctx?.permissions?.includes?.('ManageGuild')); }
function canManageChannels(ctx){ return Boolean(ctx?.isOwner || ctx?.permissions?.includes?.('Administrator') || ctx?.permissions?.includes?.('ManageChannels')); }
function canManageMessages(ctx){ return Boolean(ctx?.isOwner || ctx?.permissions?.includes?.('Administrator') || ctx?.permissions?.includes?.('ManageMessages')); }
function canManageRoles(ctx){ return Boolean(ctx?.isOwner || ctx?.permissions?.includes?.('Administrator') || ctx?.permissions?.includes?.('ManageRoles')); }

function toolDefs(){
  const f=(name,description,properties={},required=[])=>({type:'function',function:{name,description,parameters:{type:'object',properties,required,additionalProperties:false}}});
  return [
    f('set_afk','Set or clear AFK for a member. For yourself, omit user_id.',{user_id:{type:'string'},reason:{type:'string',maxLength:300},clear:{type:'boolean'}}),
    f('get_afk','Check AFK status for one member.',{user_id:{type:'string'},}),
    f('create_reminder','Create a persistent reminder for a member. Use seconds from now, or an ISO timestamp.',{text:{type:'string',minLength:1,maxLength:500},seconds:{type:'integer',minimum:10,maximum:315360000},at:{type:'string'},user_id:{type:'string'}} ,['text']),
    f('list_reminders','List reminders for a member.',{user_id:{type:'string'},include_done:{type:'boolean'}}),
    f('cancel_reminder','Cancel one reminder by ID.',{reminder_id:{type:'integer',minimum:1}} ,['reminder_id']),
    f('create_poll','Create a poll in a channel. Up to 10 options.',{channel_query:{type:'string'},question:{type:'string',minLength:1,maxLength:250},options:{type:'array',items:{type:'string',maxLength:80},minItems:2,maxItems:10},duration_seconds:{type:'integer',minimum:0,maximum:31536000}} ,['question','options']),
    f('close_poll','Close a Spark poll by channel/message ID.',{channel_id:{type:'string'},message_id:{type:'string'}} ,['channel_id','message_id']),
    f('create_giveaway','Create a timed giveaway. Entries use 🎉 reaction.',{channel_query:{type:'string'},prize:{type:'string',minLength:1,maxLength:200},duration_seconds:{type:'integer',minimum:10,maximum:3153600000},winners:{type:'integer',minimum:1,maximum:20}},['prize','duration_seconds']),
    f('end_giveaway','End a giveaway by channel/message ID.',{channel_id:{type:'string'},message_id:{type:'string'}} ,['channel_id','message_id']),
    f('set_welcome','Configure member join welcome messages in a channel.',{channel_query:{type:'string'},message:{type:'string',minLength:1,maxLength:1500},enabled:{type:'boolean'}} ,['channel_query','message']),
    f('set_goodbye','Configure member leave messages in a channel.',{channel_query:{type:'string'},message:{type:'string',minLength:1,maxLength:1500},enabled:{type:'boolean'}} ,['channel_query','message']),
    f('set_autorole','Configure a role automatically given to new members.',{role_id:{type:'string'},enabled:{type:'boolean'},delay_seconds:{type:'integer',minimum:0,maximum:86400}} ,['role_id','enabled']),
    f('set_leveling','Enable/disable XP leveling and configure XP per message/cooldown.',{enabled:{type:'boolean'},xp_per_message:{type:'integer',minimum:1,maximum:100},cooldown_seconds:{type:'integer',minimum:0,maximum:3600}} ,['enabled']),
    f('get_member_level','Get XP/level stats for a member.',{user_id:{type:'string'}}),
    f('get_level_leaderboard','Get top members by XP level.',{limit:{type:'integer',minimum:1,maximum:25}}),
    f('set_starboard','Configure the channel where highly-reacted messages are reposted as a starboard, plus the minimum ⭐ threshold.',{channel_query:{type:'string'},threshold:{type:'integer',minimum:1,maximum:20},enabled:{type:'boolean'}},['channel_query','threshold','enabled']),
    f('set_slowmode','Set a channel slowmode in seconds.',{channel_query:{type:'string'},seconds:{type:'integer',minimum:0,maximum:21600}},['channel_query','seconds']),
    f('set_channel_topic','Set a channel topic.',{channel_query:{type:'string'},topic:{type:'string',maxLength:1024}},['channel_query','topic']),
    f('rename_channel','Rename a channel.',{channel_query:{type:'string'},name:{type:'string',minLength:1,maxLength:100}},['channel_query','name']),
    f('create_invite','Create a Discord invite for a channel.',{channel_query:{type:'string'},max_age_seconds:{type:'integer',minimum:0,maximum:604800},max_uses:{type:'integer',minimum:0,maximum:100},temporary:{type:'boolean'}},[]),
    f('set_nickname','Set or clear a member nickname.',{user_id:{type:'string'},nickname:{type:'string',maxLength:32}},['user_id']),
    f('create_custom_command','Create/update a simple custom text trigger.',{trigger:{type:'string',minLength:1,maxLength:50},response:{type:'string',minLength:1,maxLength:1900}},['trigger','response']),
    f('delete_custom_command','Delete a custom text trigger.',{trigger:{type:'string'}},['trigger']),
    f('list_custom_commands','List custom text triggers.',{}),
    f('create_tag','Create/update a tag with text content.',{name:{type:'string',minLength:1,maxLength:50},content:{type:'string',minLength:1,maxLength:1900}},['name','content']),
    f('get_tag','Get a tag by name.',{name:{type:'string'}},['name']),
    f('delete_tag','Delete a tag.',{name:{type:'string'}},['name']),
    f('set_autoresponder','Create/update an autoresponder that watches messages for a trigger.',{trigger:{type:'string',minLength:1,maxLength:100},response:{type:'string',minLength:1,maxLength:1900}},['trigger','response']),
    f('delete_autoresponder','Delete an autoresponder.',{trigger:{type:'string'}},['trigger']),
    f('set_log_channel','Set a logging channel for a log group (messages, members, moderation, server).',{group:{type:'string',enum:['messages','members','moderation','server']},channel_query:{type:'string'}},['group','channel_query']),
    f('get_log_config','Get current logging configuration.',{}),
    f('set_automod','Configure basic automod switches: bad words, links, spam, mass mentions.',{enabled:{type:'boolean'},bad_words:{type:'boolean'},links:{type:'boolean'},spam:{type:'boolean'},mass_mentions:{type:'boolean'}},['enabled']),
    f('set_autopurge','Configure periodic automatic cleanup in one channel.',{channel_query:{type:'string'},interval_seconds:{type:'integer',minimum:60,maximum:604800},count:{type:'integer',minimum:1,maximum:100},enabled:{type:'boolean'}},['channel_query','interval_seconds','count','enabled']),
    f('announce','Send a formatted announcement embed to a channel.',{channel_query:{type:'string'},title:{type:'string',maxLength:256},content:{type:'string',minLength:1,maxLength:3900},mention_everyone:{type:'boolean'}},['channel_query','content']),
    f('forms_post','Post a simple form-style question panel message for members.',{channel_query:{type:'string'},title:{type:'string',maxLength:256},questions:{type:'array',items:{type:'string',maxLength:200},minItems:1,maxItems:5}},['channel_query','title','questions']),
    f('set_sticky_roles','Remember a member’s roles and restore them if they rejoin.',{user_id:{type:'string'},enabled:{type:'boolean'}},['user_id','enabled']),
    f('set_voice_role','Give/remove a role automatically when members join a specific voice channel.',{channel_query:{type:'string'},role_id:{type:'string'},enabled:{type:'boolean'}},['channel_query','role_id','enabled']),
    f('set_highlight','DM the member when a chosen keyword/phrase is mentioned in server messages they can see.',{keyword:{type:'string',minLength:1,maxLength:100},enabled:{type:'boolean'}},['keyword','enabled']),
    f('create_repeating_message','Post a repeating message on a schedule.',{channel_query:{type:'string'},content:{type:'string',minLength:1,maxLength:1900},interval_seconds:{type:'integer',minimum:60,maximum:2592000},enabled:{type:'boolean'}},['channel_query','content','interval_seconds','enabled']),
    f('create_role_menu','Post a self-role dropdown using existing roles. Members can choose which of the listed roles they want.',{channel_query:{type:'string'},title:{type:'string',maxLength:256},role_ids:{type:'array',items:{type:'string'},minItems:1,maxItems:25},multiple:{type:'boolean'}},['channel_query','title','role_ids'])
  ];
}

async function execAllBotTool(name,args,{message,memberContext,loadData,saveData}){
  const guild=message.guild; const db=loadData();
  db.afk ||= {}; db.reminders ||= {}; db.polls ||= {}; db.giveaways ||= {}; db.botConfig ||= {}; db.levels ||= {}; db.customCommands ||= {}; db.tags ||= {}; db.autoresponders ||= {}; db.logs ||= {}; db.automod ||= {}; db.autopurge ||= {}; db.stickyRoles ||= {}; db.voiceRoles ||= {}; db.highlights ||= {}; db.repeating ||= {}; db.roleMenus ||= {};
  const g=guild.id;
  const requirePerm=(ok,label)=>ok?null:{error:`Missing ${label} permission.`};
  switch(name){
    case 'set_afk': { const uid=String(args?.user_id||message.author.id); if(uid!==message.author.id && !isAdminish(memberContext)) return {error:'Only staff can set AFK for another member.'}; if(args?.clear){ delete db.afk[uid]; saveData(db); return {ok:true,cleared:true}; } db.afk[uid]={reason:clamp(args?.reason||'AFK',300),since:new Date().toISOString()}; saveData(db); return {ok:true,afk:db.afk[uid]}; }
    case 'get_afk': { const uid=String(args?.user_id||message.author.id); return {userId:uid,afk:db.afk[uid]||null}; }
    case 'create_reminder': { const uid=String(args?.user_id||message.author.id); if(uid!==message.author.id && !isAdminish(memberContext)) return {error:'Only staff can create reminders for another member.'}; const now=Date.now(); const at=args?.at?Date.parse(args.at):now+Number(args?.seconds||0)*1000; if(!Number.isFinite(at)||at<=now) return {error:'Reminder time is invalid or in the past.'}; db.reminders[g] ||= []; const id=(db.reminders[g].at(-1)?.id||0)+1; db.reminders[g].push({id,userId:uid,text:clamp(args.text,500),at,done:false,createdAt:new Date().toISOString()}); saveData(db); return {ok:true,id,at:new Date(at).toISOString()}; }
    case 'list_reminders': { const uid=String(args?.user_id||message.author.id); if(uid!==message.author.id&&!isAdminish(memberContext)) return {error:'Only staff can inspect another member reminders.'}; const rows=(db.reminders[g]||[]).filter(r=>r.userId===uid&&(!r.done||args?.include_done)).slice(-50); return {reminders:rows}; }
    case 'cancel_reminder': { const rows=db.reminders[g]||[]; const r=rows.find(x=>x.id===Number(args?.reminder_id)); if(!r)return {error:'Reminder not found.'}; if(r.userId!==message.author.id&&!isAdminish(memberContext)) return {error:'Not your reminder.'}; r.done=true;r.cancelled=true;saveData(db);return {ok:true,id:r.id}; }
    case 'create_poll': { const deny=requirePerm(message.member.permissions.has(PermissionFlagsBits.ManageMessages)||isAdminish(memberContext),'Manage Messages');if(deny)return deny;const ch=resolveChannel(guild,args.channel_query)||message.channel;if(!ch?.isTextBased?.())return {error:'Channel not found.'};const emojis=['1️⃣','2️⃣','3️⃣','4️⃣','5️⃣','6️⃣','7️⃣','8️⃣','9️⃣','🔟'];const embed=new EmbedBuilder().setTitle(`📊 ${clamp(args.question,240)}`).setDescription(args.options.map((o,i)=>`${emojis[i]} ${o}`).join('\n')).setColor('#5865F2').setFooter({text:'Vote by reacting'}).setTimestamp();const sent=await ch.send({embeds:[embed]});for(let i=0;i<args.options.length;i++)await sent.react(emojis[i]).catch(()=>{});db.polls[g]||={};db.polls[g][sent.id]={channelId:ch.id,question:args.question,options:args.options,emojis:emojis.slice(0,args.options.length),endsAt:args.duration_seconds?Date.now()+args.duration_seconds*1000:null,open:true};saveData(db);return {ok:true,messageId:sent.id,channelId:ch.id,endsAt:db.polls[g][sent.id].endsAt}; }
    case 'close_poll': { if(!isAdminish(memberContext)) return {error:'Manage Server/Administrator required.'};const ch=guild.channels.cache.get(String(args.channel_id));const p=db.polls[g]?.[String(args.message_id)];if(!ch||!p)return {error:'Poll not found.'};const m=await ch.messages.fetch(args.message_id).catch(()=>null);if(!m)return {error:'Poll message not found.'};const counts=[];for(let i=0;i<p.options.length;i++){const rc=m.reactions.cache.get(p.emojis[i]);counts.push({option:p.options[i],votes:rc?.count?Math.max(0,rc.count-1):0});}p.open=false;p.closedAt=new Date().toISOString();saveData(db);return {ok:true,counts}; }
    case 'create_giveaway': { const deny=requirePerm(message.member.permissions.has(PermissionFlagsBits.ManageMessages)||isAdminish(memberContext),'Manage Messages');if(deny)return deny;const ch=resolveChannel(guild,args.channel_query)||message.channel;if(!ch?.isTextBased?.())return {error:'Channel not found.'};const embed=new EmbedBuilder().setTitle('🎁 GIVEAWAY').setDescription(`Prize: **${clamp(args.prize,200)}**\n\nReact with 🎉 to enter!\nEnds <t:${Math.floor((Date.now()+args.duration_seconds*1000)/1000)}:R>`).setColor('#F1C40F').setTimestamp();const sent=await ch.send({embeds:[embed]});await sent.react('🎉');db.giveaways[g]||={};db.giveaways[g][sent.id]={channelId:ch.id,prize:args.prize,winners:args.winners||1,endsAt:Date.now()+args.duration_seconds*1000,ended:false};saveData(db);return {ok:true,messageId:sent.id,channelId:ch.id}; }
    case 'end_giveaway': { if(!isAdminish(memberContext))return {error:'Manage Server/Administrator required.'};const p=db.giveaways[g]?.[args.message_id];if(!p)return {error:'Giveaway not found.'};const ch=guild.channels.cache.get(p.channelId);const m=await ch?.messages.fetch(args.message_id).catch(()=>null);if(!m)return {error:'Giveaway message not found.'};const users=m.reactions.cache.get('🎉')?await m.reactions.cache.get('🎉').users.fetch():null;const pool=users?[...users.values()].filter(u=>!u.bot):[];const wins=[];for(let i=0;i<Math.min(p.winners,pool.length);i++){const j=Math.floor(Math.random()*pool.length);wins.push(pool.splice(j,1)[0].id);}p.ended=true;p.winnersSelected=wins;p.endedAt=new Date().toISOString();saveData(db);await ch.send(`🎉 Giveaway ended! Prize: **${p.prize}**\nWinner${wins.length===1?'':'s'}: ${wins.length?wins.map(id=>`<@${id}>`).join(', '):'no valid entries 😭'}`);return {ok:true,winners:wins}; }
    case 'set_welcome': { const deny=requirePerm(isAdminish(memberContext),'Manage Server');if(deny)return deny;const ch=resolveChannel(guild,args.channel_query);if(!ch)return {error:'Channel not found.'};db.botConfig[g]||={};db.botConfig[g].welcome={enabled:Boolean(args.enabled!==false),channelId:ch.id,message:clamp(args.message,1500)};saveData(db);return {ok:true,config:db.botConfig[g].welcome}; }
    case 'set_goodbye': { const deny=requirePerm(isAdminish(memberContext),'Manage Server');if(deny)return deny;const ch=resolveChannel(guild,args.channel_query);if(!ch)return {error:'Channel not found.'};db.botConfig[g]||={};db.botConfig[g].goodbye={enabled:Boolean(args.enabled!==false),channelId:ch.id,message:clamp(args.message,1500)};saveData(db);return {ok:true,config:db.botConfig[g].goodbye}; }
    case 'set_autorole': { const deny=requirePerm(canManageRoles(memberContext),'Manage Roles');if(deny)return deny;const role=guild.roles.cache.get(String(args.role_id));if(!role)return {error:'Role not found.'};if(role.managed||role.position>=guild.members.me.roles.highest.position)return {error:'Spark cannot assign that role because of role hierarchy/managed role.'};db.botConfig[g]||={};db.botConfig[g].autorole={enabled:Boolean(args.enabled),roleId:role.id,delaySeconds:Number(args.delay_seconds||0)};saveData(db);return {ok:true,config:db.botConfig[g].autorole}; }
    case 'set_leveling': { const deny=requirePerm(isAdminish(memberContext),'Manage Server');if(deny)return deny;db.botConfig[g]||={};db.botConfig[g].leveling={enabled:Boolean(args.enabled),xpPerMessage:Number(args.xp_per_message||5),cooldownSeconds:Number(args.cooldown_seconds??30)};saveData(db);return {ok:true,config:db.botConfig[g].leveling}; }
    case 'get_member_level': { const uid=String(args?.user_id||message.author.id);if(uid!==message.author.id&&!isAdminish(memberContext))return {error:'Staff only for other members.'};const row=db.levels[g]?.[uid]||{xp:0,level:0,messages:0};return {userId:uid,...row}; }
    case 'get_level_leaderboard': { const rows=Object.entries(db.levels[g]||{}).sort((a,b)=>b[1].xp-a[1].xp).slice(0,Number(args?.limit||10)).map(([id,r],i)=>({rank:i+1,userId:id,...r}));return {leaderboard:rows}; }
    case 'set_starboard': { const deny=requirePerm(canManageMessages(memberContext)||isAdminish(memberContext),'Manage Messages');if(deny)return deny;const ch=resolveChannel(guild,args.channel_query);if(!ch?.isTextBased?.())return {error:'Channel not found.'};db.botConfig[g]||={};db.botConfig[g].starboard={enabled:Boolean(args.enabled),channelId:ch.id,threshold:Number(args.threshold||3)};saveData(db);return {ok:true,config:db.botConfig[g].starboard}; }
    case 'set_slowmode': { const deny=requirePerm(canManageChannels(memberContext),'Manage Channels');if(deny)return deny;const ch=resolveChannel(guild,args.channel_query)||message.channel;if(!ch?.setRateLimitPerUser)return {error:'That channel does not support slowmode.'};await ch.setRateLimitPerUser(Number(args.seconds||0),`Spark by ${message.author.tag}`);return {ok:true,channel:ch.name,seconds:Number(args.seconds||0)}; }
    case 'set_channel_topic': { const deny=requirePerm(canManageChannels(memberContext),'Manage Channels');if(deny)return deny;const ch=resolveChannel(guild,args.channel_query)||message.channel;if(!ch?.setTopic)return {error:'That channel has no topic.'};await ch.setTopic(clamp(args.topic,1024),`Spark by ${message.author.tag}`);return {ok:true,channel:ch.name}; }
    case 'rename_channel': { const deny=requirePerm(canManageChannels(memberContext),'Manage Channels');if(deny)return deny;const ch=resolveChannel(guild,args.channel_query)||message.channel;if(!ch)return {error:'Channel not found.'};await ch.setName(String(args.name).replace(/[^a-zA-Z0-9- _]/g,'').trim().slice(0,100),`Spark by ${message.author.tag}`);return {ok:true,channel:ch.name}; }
    case 'create_invite': { const deny=requirePerm(message.member.permissions.has(PermissionFlagsBits.CreateInstantInvite)||isAdminish(memberContext),'Create Instant Invite');if(deny)return deny;const ch=resolveChannel(guild,args.channel_query)||message.channel;if(!ch?.createInvite)return {error:'Cannot create invite in this channel.'};const invite=await ch.createInvite({maxAge:Number(args.max_age_seconds||3600),maxUses:Number(args.max_uses||0),temporary:Boolean(args.temporary),reason:`Spark by ${message.author.tag}`});return {ok:true,code:invite.code,url:invite.url}; }
    case 'set_nickname': { const deny=requirePerm(isAdminish(memberContext)||message.member.permissions.has(PermissionFlagsBits.ManageNicknames),'Manage Nicknames');if(deny)return deny;const target=resolveMember(guild,args.user_id);if(!target)return {error:'Member not found.'};if(!memberContext.isOwner&&!isAdminish(memberContext)&&target.id!==message.author.id)return {error:'You may only change your own nickname.'};await target.setNickname(args.nickname?String(args.nickname).slice(0,32):null,`Spark by ${message.author.tag}`);return {ok:true,userId:target.id,nickname:target.nickname||null}; }
    case 'create_custom_command': { const deny=requirePerm(isAdminish(memberContext),'Manage Server');if(deny)return deny;const t=String(args.trigger).toLowerCase().replace(/^[/!?.]+/,'');db.customCommands[g]||={};db.customCommands[g][t]={response:clamp(args.response),updatedAt:new Date().toISOString(),updatedBy:message.author.id};saveData(db);return {ok:true,trigger:t}; }
    case 'delete_custom_command': { const deny=requirePerm(isAdminish(memberContext),'Manage Server');if(deny)return deny;const t=String(args.trigger).toLowerCase().replace(/^[/!?.]+/,'');if(!db.customCommands[g]?.[t])return {error:'Custom command not found.'};delete db.customCommands[g][t];saveData(db);return {ok:true,deleted:t}; }
    case 'list_custom_commands': return {commands:Object.keys(db.customCommands[g]||{})};
    case 'create_tag': { const deny=requirePerm(isAdminish(memberContext),'Manage Server');if(deny)return deny;const n=String(args.name).toLowerCase().replace(/\s+/g,'-');db.tags[g]||={};db.tags[g][n]={content:clamp(args.content),updatedAt:new Date().toISOString(),updatedBy:message.author.id};saveData(db);return {ok:true,name:n}; }
    case 'get_tag': { const n=String(args.name).toLowerCase();return db.tags[g]?.[n]?{ok:true,name:n,...db.tags[g][n]}:{error:'Tag not found.'}; }
    case 'delete_tag': { const deny=requirePerm(isAdminish(memberContext),'Manage Server');if(deny)return deny;const n=String(args.name).toLowerCase();if(!db.tags[g]?.[n])return {error:'Tag not found.'};delete db.tags[g][n];saveData(db);return {ok:true,deleted:n}; }
    case 'set_autoresponder': { const deny=requirePerm(isAdminish(memberContext),'Manage Server');if(deny)return deny;const t=String(args.trigger).toLowerCase();db.autoresponders[g]||={};db.autoresponders[g][t]={response:clamp(args.response),updatedAt:new Date().toISOString()};saveData(db);return {ok:true,trigger:t}; }
    case 'delete_autoresponder': { const deny=requirePerm(isAdminish(memberContext),'Manage Server');if(deny)return deny;const t=String(args.trigger).toLowerCase();if(!db.autoresponders[g]?.[t])return {error:'Autoresponder not found.'};delete db.autoresponders[g][t];saveData(db);return {ok:true,deleted:t}; }
    case 'set_log_channel': { const deny=requirePerm(isAdminish(memberContext),'Manage Server');if(deny)return deny;const ch=resolveChannel(guild,args.channel_query);if(!ch)return {error:'Channel not found.'};db.logs[g]||={};db.logs[g][args.group]=ch.id;saveData(db);return {ok:true,group:args.group,channelId:ch.id}; }
    case 'get_log_config': return {config:db.logs[g]||{}};
    case 'set_automod': { const deny=requirePerm(isAdminish(memberContext),'Manage Server');if(deny)return deny;db.automod[g]={enabled:Boolean(args.enabled),badWords:args.bad_words!==false,links:args.links!==false,spam:args.spam!==false,massMentions:args.mass_mentions!==false};saveData(db);return {ok:true,config:db.automod[g]}; }
    case 'set_autopurge': { const deny=requirePerm(canManageMessages(memberContext),'Manage Messages');if(deny)return deny;const ch=resolveChannel(guild,args.channel_query);if(!ch?.isTextBased?.())return {error:'Channel not found.'};db.autopurge[g]||={};db.autopurge[g][ch.id]={enabled:Boolean(args.enabled),intervalSeconds:Number(args.interval_seconds),count:Number(args.count)};saveData(db);return {ok:true,channelId:ch.id,config:db.autopurge[g][ch.id]}; }
    case 'announce': { const deny=requirePerm(isAdminish(memberContext),'Manage Server');if(deny)return deny;const ch=resolveChannel(guild,args.channel_query);if(!ch?.isTextBased?.())return {error:'Channel not found.'};const embed=new EmbedBuilder().setTitle(clamp(args.title||'NETHRION ANNOUNCEMENT',256)).setDescription(clamp(args.content,3900)).setColor('#5865F2').setTimestamp().setFooter({text:`Posted by ${message.author.username}`});const payload={embeds:[embed]};if(args.mention_everyone===true)payload.content='@everyone';const sent=await ch.send(payload);return {ok:true,messageId:sent.id,channelId:ch.id}; }
    case 'forms_post': { const deny=requirePerm(isAdminish(memberContext),'Manage Server');if(deny)return deny;const ch=resolveChannel(guild,args.channel_query);if(!ch?.isTextBased?.())return {error:'Channel not found.'};const embed=new EmbedBuilder().setTitle(clamp(args.title||'Form',256)).setDescription(args.questions.map((q,i)=>`${i+1}. ${clamp(q,200)}`).join('\n')).setColor('#2b2d31');const sent=await ch.send({embeds:[embed]});return {ok:true,messageId:sent.id,channelId:ch.id}; }
    case 'set_sticky_roles': { const deny=requirePerm(isAdminish(memberContext),'Manage Server');if(deny)return deny;const uid=String(args.user_id);db.stickyRoles[g] ||= {};if(args.enabled){const m=await guild.members.fetch(uid).catch(()=>null);if(!m)return {error:'Member not found.'};db.stickyRoles[g][uid]={enabled:true,roleIds:[...m.roles.cache.keys()].filter(id=>id!==guild.id)};}else{delete db.stickyRoles[g][uid];}saveData(db);return {ok:true,userId:uid,config:db.stickyRoles[g][uid]||null}; }
    case 'set_voice_role': { const deny=requirePerm(canManageRoles(memberContext),'Manage Roles');if(deny)return deny;const ch=resolveChannel(guild,args.channel_query);const role=guild.roles.cache.get(String(args.role_id));if(!ch||ch.type!==ChannelType.GuildVoice)return {error:'Voice channel not found.'};if(!role||role.managed||role.position>=guild.members.me.roles.highest.position)return {error:'Role not found or Spark cannot manage it.'};db.voiceRoles[g] ||= {};if(args.enabled)db.voiceRoles[g][ch.id]={roleId:role.id};else delete db.voiceRoles[g][ch.id];saveData(db);return {ok:true,channelId:ch.id,roleId:args.enabled?role.id:null}; }
    case 'set_highlight': { const uid=message.author.id;db.highlights[g] ||= {};const k=String(args.keyword).toLowerCase();db.highlights[g][uid] ||= {};if(args.enabled)db.highlights[g][uid][k]={keyword:args.keyword,enabled:true};else delete db.highlights[g][uid][k];saveData(db);return {ok:true,keyword:args.keyword,enabled:Boolean(args.enabled)}; }
    case 'create_repeating_message': { const deny=requirePerm(isAdminish(memberContext),'Manage Server');if(deny)return deny;const ch=resolveChannel(guild,args.channel_query);if(!ch?.isTextBased?.())return {error:'Channel not found.'};db.repeating[g] ||= {};const id=(Object.keys(db.repeating[g]).length?Math.max(...Object.keys(db.repeating[g]).map(Number)):0)+1;db.repeating[g][id]={id,channelId:ch.id,content:clamp(args.content),intervalSeconds:Number(args.interval_seconds),enabled:Boolean(args.enabled),lastSentAt:0,createdBy:message.author.id};saveData(db);return {ok:true,id,channelId:ch.id}; }
    case 'create_role_menu': { const deny=requirePerm(canManageRoles(memberContext),'Manage Roles');if(deny)return deny;const ch=resolveChannel(guild,args.channel_query)||message.channel;if(!ch?.isTextBased?.())return {error:'Channel not found.'};const roles=args.role_ids.map(id=>guild.roles.cache.get(String(id))).filter(r=>r&&!r.managed&&r.id!==guild.id&&r.position<guild.members.me.roles.highest.position);if(!roles.length)return {error:'No manageable roles found.'};const menuId=`spark_roles_${Date.now()}`;const menu=new StringSelectMenuBuilder().setCustomId(menuId).setPlaceholder('Choose your roles...').setMinValues(args.multiple===false?1:0).setMaxValues(Math.min(args.multiple===false?1:roles.length,25)).addOptions(roles.map(r=>new StringSelectMenuOptionBuilder().setLabel(r.name.slice(0,100)).setValue(r.id)));const sent=await ch.send({embeds:[new EmbedBuilder().setTitle(clamp(args.title||'Choose Roles',256)).setDescription('Pick the roles you want. You can change them anytime.').setColor('#5865F2')],components:[new ActionRowBuilder().addComponents(menu)]});db.roleMenus[g] ||= {};db.roleMenus[g][sent.id]={roleIds:roles.map(r=>r.id),multiple:args.multiple!==false};saveData(db);return {ok:true,messageId:sent.id,channelId:ch.id,roles:roles.map(r=>({id:r.id,name:r.name}))}; }
    default: return null;
  }
}

async function tickAutomation(guild, client, loadData, saveData){
  const db=loadData(); const g=guild.id; let changed=false;
  const reminders=db.reminders?.[g]||[]; for(const r of reminders){ if(r.done||r.at>Date.now())continue; const ch=guild.systemChannel||guild.channels.cache.find(c=>c.isTextBased?.()); const target=guild.members.cache.get(r.userId); if(ch&&target){await ch.send(`⏰ <@${r.userId}> reminder: ${r.text}`).catch(()=>{});} r.done=true;r.completedAt=new Date().toISOString();changed=true; }
  for(const [mid,p] of Object.entries(db.giveaways?.[g]||{})){ if(p.ended||p.endsAt>Date.now())continue; const ch=guild.channels.cache.get(p.channelId);const m=await ch?.messages.fetch(mid).catch(()=>null); if(m){const users=m.reactions.cache.get('🎉')?await m.reactions.cache.get('🎉').users.fetch():null;const pool=users?[...users.values()].filter(u=>!u.bot):[];const wins=[];for(let i=0;i<Math.min(p.winners,pool.length);i++){const j=Math.floor(Math.random()*pool.length);wins.push(pool.splice(j,1)[0].id);}p.ended=true;p.winnersSelected=wins;p.endedAt=new Date().toISOString();await ch.send(`🎉 Giveaway ended! Prize: **${p.prize}**\nWinner${wins.length===1?'':'s'}: ${wins.length?wins.map(id=>`<@${id}>`).join(', '):'no valid entries 😭'}`).catch(()=>{});changed=true;} }
  for(const [mid,p] of Object.entries(db.polls?.[g]||{})){ if(!p.open||!p.endsAt||p.endsAt>Date.now())continue; const ch=guild.channels.cache.get(p.channelId);const m=await ch?.messages.fetch(mid).catch(()=>null);if(m){const counts=[];for(let i=0;i<p.options.length;i++){const rc=m.reactions.cache.get(p.emojis[i]);counts.push({option:p.options[i],votes:rc?.count?Math.max(0,rc.count-1):0});}p.open=false;p.closedAt=new Date().toISOString();const best=counts.slice().sort((a,b)=>b.votes-a.votes)[0];await ch.send(`📊 Poll closed — **${best?.option||'no votes'}** won with ${best?.votes||0} votes.`).catch(()=>{});changed=true;} }
  for(const item of Object.values(db.autopurge?.[g]||{})){ if(!item.enabled||Date.now()-(item.lastRunAt||0)<item.intervalSeconds*1000) continue; const ch=guild.channels.cache.get(item.channelId); if(ch?.isTextBased?.()){const msgs=await ch.messages.fetch({limit:Math.min(Number(item.count)||10,100)}).catch(()=>null);if(msgs?.size){await ch.bulkDelete(msgs,true).catch(()=>{});}item.lastRunAt=Date.now();changed=true;} }
  for(const item of Object.values(db.repeating?.[g]||{})){ if(!item.enabled||Date.now()-(item.lastSentAt||0)<item.intervalSeconds*1000) continue; const ch=guild.channels.cache.get(item.channelId); if(ch?.isTextBased?.()){await ch.send(item.content).catch(()=>{});item.lastSentAt=Date.now();changed=true;} }
  if(changed)saveData(db);
}

module.exports={toolDefs,execAllBotTool,tickAutomation};
